name: C++ CI with Allure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y g++ cmake libgtest-dev

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run ForwardList tests
        run: |
          mkdir -p test-reports
          cd build
          ./test_ForwardList --gtest_output=xml:../test-reports/forwardlist.xml

      - name: Run CircularDLL tests
        run: |
          cd build
          ./test_CircularDLL --gtest_output=xml:../test-reports/circulardll.xml

      - name: Run BinarySearchTree tests
        run: |
          cd build
          ./test_BinarySearchTree --gtest_output=xml:../test-reports/binarysearchtree.xml

      - name: Run HashSet tests
        run: |
          cd build
          ./test_HashSet --gtest_output=xml:../test-reports/hashset.xml

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          curl -sL https://github.com/allure-framework/allure2/releases/download/2.20.0/allure-2.20.0.tgz | tar -xz
          sudo mv allure-2.20.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate Allure Report
        run: |
          allure generate test-reports -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
