name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y g++ cmake libgtest-dev

    - name: Build and run tests
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ctest --output-on-failure
