name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up C++ environment
      uses: actions/setup-cpp@v1
      with:
        compiler: g++

    - name: Install dependencies
      run: sudo apt-get install -y libgtest-dev cmake

    - name: Build and run tests
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ./runTests
