name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y g++ cmake libgtest-dev

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run tests and generate JUnit reports
        run: |
          cd build
          # Ejecutar cada prueba y generar un archivo XML
          ./test_DLinkedList --gtest_output="xml:test_DLinkedList_results.xml"
          ./test_ForwardList --gtest_output="xml:test_ForwardList_results.xml"
          ./test_CircularDLL --gtest_output="xml:test_CircularDLL_results.xml"
          ./test_BinarySearchTree --gtest_output="xml:test_BinarySearchTree_results.xml"
          ./test_HashTable_Set --gtest_output="xml:test_HashTable_Set_results.xml"
          ./test_hashTable_map --gtest_output="xml:test_hashTable_map_results.xml"

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: 'build/*_results.xml' # Procesa todos los XML