name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y g++ cmake libgtest-dev

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run DLinkedList tests
        run: |
          cd build
          ./test_DLinkedList

      - name: Run ForwardList tests
        run: |
          cd build
          ./test_ForwardList

      - name: Run CircularDLL tests
        run: |
          cd build
          ./test_CircularDLL

      - name: Run BinarySearchTree tests
        run: |
          cd build
          ./test_BinarySearchTree

      - name: Run HashTable_Set tests
        run: |
          cd build
          ./test_HashTable_Set

      - name: Run HashTable_Map tests
        run: |
          cd build
          ./test_HashTable_Map
