name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Permisos necesarios para publicar los reports
    permissions:
      checks: write    # Permite crear checks en PRs
      actions: write   # Permite actualizar el job
      statuses: write  # Permite actualizar el estado

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y g++ cmake libgtest-dev

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run tests and generate JUnit reports
        run: |
          cd build
          # Genera un XML por cada suite de pruebas
          ./test_DLinkedList --gtest_output="xml:test_DLinkedList.xml"
          ./test_ForwardList --gtest_output="xml:test_ForwardList.xml"
          ./test_CircularDLL --gtest_output="xml:test_CircularDLL.xml"
          ./test_BinarySearchTree --gtest_output="xml:test_BinarySearchTree.xml"
          ./test_HashTable_Set --gtest_output="xml:test_HashTable_Set.xml"
          ./test_hashTable_map --gtest_output="xml:test_hashTable_map.xml"

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: |
            build/test_DLinkedList.xml
            build/test_ForwardList.xml
            build/test_CircularDLL.xml
            build/test_BinarySearchTree.xml
            build/test_HashTable_Set.xml
            build/test_hashTable_map.xml
          check_title: "JUnit Test Report"
          fail_on_failure: false