name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write   # Necesario para crear checks
      actions: write
      contents: read  # Necesario para clonar el repo

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake libgtest-dev jq

      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run tests and generate reports
        run: |
          cd build
          # Generar XML para cada test
          ./test_DLinkedList --gtest_output="xml:DLinkedList.xml"
          ./test_ForwardList --gtest_output="xml:ForwardList.xml"
          ./test_CircularDLL --gtest_output="xml:CircularDLL.xml"
          ./test_BinarySearchTree --gtest_output="xml:BinarySearchTree.xml"
          ./test_HashTable_Set --gtest_output="xml:HashTable_Set.xml"
          ./test_hashTable_map --gtest_output="xml:HashTable_Map.xml"

      - name: Publish individual test reports
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd build
          # Lista de todos los reports generados
          REPORTS=(
            "DLinkedList.xml"
            "ForwardList.xml"
            "CircularDLL.xml"
            "BinarySearchTree.xml"
            "HashTable_Set.xml"
            "HashTable_Map.xml"
          )

          for REPORT in "${REPORTS[@]}"; do
            if [ -f "$REPORT" ]; then
              # Extraer nombre del test suite
              SUITE_NAME=$(basename "$REPORT" .xml)
          
              # Contar fallos
              FAILURES=$(xmllint --xpath 'string(//testsuite/@failures)' "$REPORT")
              ERROR=$(xmllint --xpath 'string(//testsuite/@errors)' "$REPORT")
          
              # Determinar conclusión
              CONCLUSION="success"
              if [ "$FAILURES" -gt 0 ] || [ "$ERROR" -gt 0 ]; then
                CONCLUSION="failure"
              fi

              # Crear check individual
              gh api repos/${{ github.repository }}/check-runs \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                -f name="Test Suite: $SUITE_NAME" \
                -f status="completed" \
                -f conclusion="$CONCLUSION" \
                -f output="$(jq -n \
                  --arg title "$SUITE_NAME Test Results" \
                  --arg summary "$(xmllint --xpath '//testsuite/@name' "$REPORT")" \
                  --arg text "$(cat $REPORT)" \
                  '{title: $title, summary: $summary, text: $text}')"
            fi
          done